### ISSUE TITLE
Windows 10  issue in opening images

### ISSUE THREAD

**Issue by medmedmedic** [stevetasticsteve/Anki_bulk_importer#7]
Thank you for the update.
But there is still trouble finding .png images in Windows 10 OS.  
![image](https://user-images.githubusercontent.com/52632933/118919359-fb079600-b951-11eb-945a-091f1afe9553.png)

After replacing with "Image files|*.jpeg; *.jpg; *.png" its showing up. may be OS-specific
![image](https://user-images.githubusercontent.com/52632933/118925060-ac5ef980-b95b-11eb-908b-6255d53d8395.png)

_Originally posted by @medmedmedic in https://github.com/stevetasticsteve/Anki_bulk_importer/issues/6#issuecomment-844713691_

**Comment by stevetasticsteve** [comment]
Oops.
I was trying to be clever. Linux is case sensitive regarding file extensions (Windows is not), I tried to used file globbing to match upper and lower case, but Windows doesn't use file globbing.

I just made it explicit in a nasty, repetitive line of code- but it works. Thanks for testing it with Windows, appreciate it!
