### ISSUE TITLE
Bulk import in the Response field?

### ISSUE THREAD

**Issue by Kruglianin** [stevetasticsteve/Anki_bulk_importer#8]
Hi Guys.
Thanks for the great job!
Can we also implement bulk import in the "Response" field?
With any arbitrary file with any name "response.txt" or "response.csv", where the required data would be written.
Thanks for the reply!

**Comment by stevetasticsteve** [comment]
Hey

Thanks for the idea. I created this just to do one specific thing that we needed, but I've been getting a few requests to generalize it a bit more. 

So if I understand right you'd like a load button above the response column that behaves the same as the audio/image load buttons, but pulls text in.

Is that the idea?

**Comment by Kruglianin** [comment]
> Hey
> 
> Thanks for the idea. I created this just to do one specific thing that we needed, but I've been getting a few requests to generalize it a bit more.
> 
> So if I understand right you'd like a load button above the response column that behaves the same as the audio/image load buttons, but pulls text in.
> 
> Is that the idea?

Yes, you are absolutely right!
It would be very useful for my tasks.

PS. As another auxiliary option for such an operation, it would be possible by copying data cells (for example from Excel (Libre Office) or a text editor) to paste the content into each individual cell of Response field, for example through a special shortcut.
But it may be superfluous, so the first option (with a list of words from a file) seems to me would be more appropriate and more in keeping with the spirit of the addon.
Sorry, my English with the translator.

**Comment by stevetasticsteve** [comment]
I've implemented the requested feature. If you updated the addon to v.1.2 you can give it a go and let me know if it works for you. You should be able to load from a csv. It'll default to just reading the first column of the .csv file you give it. I just went in and quickly implemented it. The code needs a good refactor as I've learned a lot since I first wrote this several years ago, but I wanted to get something that works for you up quickly.

**Comment by Kruglianin** [comment]
Hello.
Many thanks for the help!
Everything works perfectly!
![image](https://user-images.githubusercontent.com/55271215/186664656-73566b13-a22f-4465-a527-47687aa4c524.png)
![image](https://user-images.githubusercontent.com/55271215/186664825-5060b448-ee53-4043-8d6f-240a9651db74.png)
